/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HOMEWORK1.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

class AppTest {
    @Test void testGetMessage() {
        App classUnderTest =new App();
        assertEquals("Hello      World!", MessageUtils.getMessage());
    }


@Test
public void Test(){
    ArrayList <Integer> arraylist=new ArrayList<Integer>();
    ArrayList <Integer> arraylist2=new ArrayList<Integer>();
   
    assertFalse(arraylist2.equals(App.sort(arraylist,"Sort",2,3,false))); //sona 3 ekledi
}

public void ControlLength() {
    ArrayList <Integer> arraylist=new ArrayList <Integer>();
    ArrayList <Integer> arraylist2=new ArrayList<Integer>();
    ArrayList <Integer> arraylist3 =new ArrayList<Integer>();
    arraylist2.add(2); //length 1 

    arraylist3= App.sort(arraylist,"Sort",2,3,false);

    
        assertTrue(arraylist3.size()==arraylist2.size());

}


public void Test3() { 
    ArrayList <Integer> arraylist =new ArrayList<Integer>();
    arraylist.add(1);
    arraylist.add(2);
    arraylist.add(4);
    arraylist.add(5);
    
    ArrayList <Integer> arraylist2 =new ArrayList<Integer>();
    arraylist2.add(2);
    arraylist2.add(4);
    arraylist2.add(5);
    arraylist2.add(3);
    assertTrue(arraylist2.equals(App.sort(arraylist,"Sort",3,1,false)));
    
}

public void Test4() {
    ArrayList <Integer> arraylist2 =new ArrayList<Integer>();
    arraylist2.add(1);
    arraylist2.add(2);
    arraylist2.add(4);
    arraylist2.add(5);
    ArrayList <Integer> arraylist3=new ArrayList <Integer>();
    arraylist3.add(2);
    arraylist3.add(3);
    arraylist3.add(4);
    arraylist3.add(5);
    
    assertTrue(arraylist3.equals(App.sort(arraylist2,"Sort",3,1,true)));
}

public void Test5 () {
    ArrayList <Integer> arraylist2 =new ArrayList<Integer>();
    arraylist2.add(1);
    arraylist2.add(2);
    arraylist2.add(4);
    arraylist2.add(5);
    ArrayList <Integer> arraylist3=new ArrayList <Integer>();
    arraylist3.add(5);
    arraylist3.add(4);
    arraylist3.add(2);
    arraylist3.add(3);

    assertTrue(arraylist3.equals(App.sort(arraylist2,"Reverse Sort",3,1,false)));
}


}
